### ISSUE TITLE
Error using bathy.style = "" except with default included rbb or rgb

### ISSUE THREAD

**Issue by calvinsbeale** [MikkoVihtakari/ggOceanMapsLargeData#1]
Hi Mikko,

plotting any map, limits don't matter, i can plot with the included "rbb" or "rbg" but none of the other options work. It seems the issue is downloading the data onto my computer.
This works:
```
basemap(limits = c(172, -178, -40, -15), 
        rotate = TRUE,
        lat.interval = 5,
        lon.interval = 2,
        bathy.style = "rbb",
        legends = FALSE)
```

This does not work:
```
basemap(limits = c(172, -178, -40, -15), 
        rotate = TRUE,
        lat.interval = 5,
        lon.interval = 2,
        bathy.style = "raster_continuous_blues",
        legends = FALSE)
```

The error given is:
Error in parse(text = k) : <text>:1:4: unexpected symbol 
1: C:\Users
        ^
>

Now this sounds like an issue on my machine yes, but i have no issue downloading packages, or files from within other packages.
I went through and changed the save location:
usethis::edit_r_profile()
• Modify 'C:/Users/User/Documents/.Rprofile'

added two lines:
.ggOceanMapsenv <- new.env()
.ggOceanMapsenv$datapath <- 'E:/R/ggOceanMaps/'

• Restart R for changes to take effect

And the error is consistent, but changes directory:
Error in parse(text = k) : <text>:1:4: unexpected symbol
1: E:\R
       ^
> 

If the directory doesn't exist i get a prompt to create it:
ggOceanMaps.datapath is pointing to E:/R/ggOceanMaps/, which does not exist. Do you want to create the directory?

1: Yes
2: No

Selection: 1
The ggOceanMaps.datapath directory created to E:/R/ggOceanMaps/
Error in parse(text = k) : <text>:1:4: unexpected symbol
1: E:\R
       ^
In addition: Warning message:
In dir.create(getOption("ggOceanMaps.datapath")) :
  cannot create dir 'E:\R\ggOceanMaps', reason 'No such file or directory'

Is there a way to fix this?
Is it possible to download the files manually to go around this issue, so I can use them for now?

Thanks

**Comment by MikkoVihtakari** [comment]
Sorry that you lost time with this. This is a known issue with the CRAN version of ggOceanMaps. My bad forgetting that Windows file separators are the other way around than in UNIX (I didn't have a Windows machine to test). It has been fixed on the GitHub version of ggOceanMaps: https://github.com/MikkoVihtakari/ggOceanMaps

Do `remotes::install_github("MikkoVihtakari/ggOceanMaps")`, delete all the content in your ggOceanMapsLargeData folder (`E:/R/ggOceanMaps/` in your case) and it should work. Please reopen if it does not.

**Comment by calvinsbeale** [comment]
Perfect thank you! Solved the problem

by the way in the help file you write:
"poly_binned_blues", "poly_blues", "pbb" or "pb" plots polygon bathymetry filled with different shades of blue. Default in the versions older than 2.0 of ggOceanMaps. Requires a download.

but "poly_binned_blues" and "pbb" do not work. "poly_blues" and "pb" do work. Just for your info.

**Comment by MikkoVihtakari** [comment]
Thanks for testing. I'll submit a fix to that shortly.

**Comment by MikkoVihtakari** [comment]
This should fix the latter issue: https://github.com/MikkoVihtakari/ggOceanMaps/commit/e5211881509826954e78fe8d897d5f555ca0026e

I also updated CRAN and the former issue should not occur any longer when uploading the package from CRAN (give CRAN a day to make the Windows binaries).
